SET SERVEROUTPUT ON FORMAT WRAPPED
SET FEEDBACK OFF
SET TRIM ON
SET TRIMSPOOL ON

spool &1
DECLARE
  V_ENCLOSURE VARCHAR2(1) := '"';
  V_SEPARATOR VARCHAR2(1) := ',';

  $IF DBMS_DB_VERSION.VER_LE_11
  $THEN 
    CURSOR OBJS IS
      SELECT OWNER,
             SYNONYM_NAME,
             TABLE_OWNER,
             TABLE_NAME,
             DB_LINK,
             NULL CON_ID_CSV
      FROM   dba_synonyms WHERE OWNER IN ('APEX_040200','APPQOSSYS','DBSNMP','DVSYS','FLOWS_FILES','PUBLIC','SI_INFORMTN_SCHEMA','SYS','SYSTEM')
      ORDER  BY 1,2,3,4;
  $ELSE
    CURSOR OBJS IS
      SELECT OWNER,
             SYNONYM_NAME,
             TABLE_OWNER,
             TABLE_NAME,
             DB_LINK,
             ORIGIN_CON_ID CON_ID_CSV -- Con ID to generate inside CSV file
      FROM   cdb_synonyms WHERE OWNER IN ('APEX_040200','APPQOSSYS','DBSNMP','DVSYS','FLOWS_FILES','PUBLIC','SI_INFORMTN_SCHEMA','SYS','SYSTEM')
      AND    (ORIGIN_CON_ID=CON_ID -- FOR NON-CDBS OR CONNECTED TO ROOT DB
      OR     SYS_CONTEXT('USERENV', 'CON_ID') > 1) -- WHEN CONNECTED TO PDB
      ORDER  BY 1,2,3,4;
  $END

  FUNCTION QA (IN_VALUE IN VARCHAR2) RETURN VARCHAR2 AS
    OUT_VALUE   VARCHAR2(4000);
  BEGIN
    IF IN_VALUE IS NOT NULL THEN
      OUT_VALUE := REPLACE(REPLACE(IN_VALUE,CHR(13),' '),CHR(10),' ');
      IF OUT_VALUE LIKE '%' || V_ENCLOSURE || '%' OR OUT_VALUE LIKE '%' || V_SEPARATOR || '%' THEN
        RETURN V_ENCLOSURE || REPLACE(OUT_VALUE,V_ENCLOSURE,V_ENCLOSURE || V_ENCLOSURE) || V_ENCLOSURE;
      ELSE
        RETURN OUT_VALUE;
      END IF;
    ELSE
      RETURN NULL;
    END IF;
  END;

BEGIN
  DBMS_OUTPUT.ENABLE(NULL);

  FOR I IN OBJS
  LOOP
    DBMS_OUTPUT.PUT_LINE(
    QA(I.OWNER) || V_SEPARATOR ||
    QA(I.SYNONYM_NAME) || V_SEPARATOR ||
    QA(I.TABLE_OWNER) || V_SEPARATOR ||
    QA(I.TABLE_NAME) || V_SEPARATOR ||
    QA(I.DB_LINK) || V_SEPARATOR ||
    QA(I.CON_ID_CSV));
  END LOOP;
END;
/

SPOOL OFF